# -*- coding: utf-8 -*-
"""Gen Z Mental Wellness using DNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/antniooliveiraa/gen-z-mental-wellness-using-dnn.9cb47154-8501-467b-8ab2-179ac92df909.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260404/auto/storage/goog4_request%26X-Goog-Date%3D20260404T011929Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D74ad45d044e0bf25d1def332ede03671a7334767bac8b9e96d74d3188d399c9bc0db18cfe764689df33128b76a3f153167df032f5506f61410b4b8a414dd1664ef3c4231aaf0587f338d2f1caaf65cf4b6cda3dc2e0a4e3bf9ee5f817c147847c4f5e66d6996407bf1c7715e5660fd64876c1e22c8763f099a8b48ffde6b48b3ceaf46de545d02e3f79e966c0c9d094a899fc6efb926c959ed80d7da977ae73e015261ca86ef7612e036533428f3f902d66b7f6d093e08f6d62323982a8ac52112b6c5c3dd718fce8fe073d8f0724545a6aaa3a34e9e5fcdadab86e871d5316243f6d784074a39628c314871c44b048dbcbd49d6d0ecf80ab96976703b6c4ed0
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
# import kagglehub
# hammadansari7_gen_z_mental_wellness_and_digital_lifestyle_patterns_path = kagglehub.dataset_download('hammadansari7/gen-z-mental-wellness-and-digital-lifestyle-patterns')
# print('Data source import complete.')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('../data/genz_mental_wellness_synthetic_dataset.csv')

# --- TRADUÇÃO PARA PT-BR ---
traducoes_colunas = {
    'Age': 'Idade',
    'Gender': 'Gênero',
    'Country': 'País',
    'Student_Working_Status': 'Status_Estudante_Trabalho',
    'Daily_Social_Media_Hours': 'Horas_Redes_Sociais_Diarias',
    'Screen_Time_Hours': 'Horas_Tempo_Tela',
    'Night_Scrolling_Frequency': 'Frequência_Scrolling_Noturno',
    'Online_Gaming_Hours': 'Horas_Jogos_Online',
    'Content_Type_Preference': 'Preferência_Tipo_Conteúdo',
    'Exercise_Frequency_per_Week': 'Frequência_Exercício_Semana',
    'Daily_Sleep_Hours': 'Horas_Sono_Diário',
    'Caffeine_Intake_Cups': 'Consumo_Cafeína_Xícaras',
    'Study_Work_Hours_per_Day': 'Horas_Estudo_Trabalho_Dia',
    'Overthinking_Score': 'Score_Pensamento_Excessivo',
    'Anxiety_Score': 'Score_Ansiedade',
    'Mood_Stability_Score': 'Score_Estabilidade_Humor',
    'Social_Comparison_Index': 'Índice_Comparação_Social',
    'Sleep_Quality_Score': 'Score_Qualidade_Sono',
    'Motivation_Level': 'Nível_Motivação',
    'Emotional_Fatigue_Score': 'Score_Fadiga_Emocional',
    'Wellbeing_Index': 'Índice_Bem_Estar',
    'Burnout_Risk': 'Risco_Burnout'
}

traducoes_valores = {
    'Gênero': {'Male': 'Masculino', 'Female': 'Feminino', 'Other': 'Outro', 'Non-binary': 'Não-binário'},
    'Status_Estudante_Trabalho': {'Working': 'Trabalhando', 'Student': 'Estudante', 'Both': 'Ambos'},
    'Preferência_Tipo_Conteúdo': {
        'News': 'Notícias', 
        'Gaming': 'Jogos', 
        'Entertainment': 'Entretenimento', 
        'Educational': 'Educativo', 
        'Lifestyle': 'Estilo de Vida'
    },
    'Risco_Burnout': {'Low': 'Baixo', 'Medium': 'Médio', 'High': 'Alto'}
}

# Aplicando as traduções
df.rename(columns=traducoes_colunas, inplace=True)
for col, mapa in traducoes_valores.items():
    if col in df.columns:
        df[col] = df[col].replace(mapa)

pd.set_option("display.max_columns",None)
df.shape

df.head()

df.info()

# EDA Visualization
sns.set_style('whitegrid')
sns.set_palette('deep')

# Pais de Origem
sns.countplot(x=df['País'])
plt.title("Distribuição por País")
plt.xlabel("País")
plt.ylabel("Contagem")
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/distribuicao_pais.png')
plt.show()

# Status de Estudante/Trabalho
sns.countplot(x=df['Status_Estudante_Trabalho'])
plt.title("Status de Estudante/Trabalho")
plt.xlabel("Status")
plt.ylabel("Contagem")
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/status_estudante.png')
plt.show()

# Gênero
sns.histplot(df['Gênero'])
plt.title("Distribuição por Gênero")
plt.xlabel("Gênero")
plt.ylabel("Contagem")
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/distribuicao_genero.png')
plt.show()

# Preferência de Conteúdo
sns.histplot(df['Preferência_Tipo_Conteúdo'])
plt.title("Preferência de Tipo de Conteúdo")
plt.xlabel("Tipo de Conteúdo")
plt.ylabel("Contagem")
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/preferencia_conteudo.png')
plt.show()

# Tempo de Tela vs Scrolling Noturno
sns.scatterplot(x ='Horas_Tempo_Tela',y ='Frequência_Scrolling_Noturno', hue ='Status_Estudante_Trabalho',data = df,size = 1)
plt.title("Tempo de Tela vs Frequência de Scrolling Noturno")
plt.xlabel("Horas de Tela")
plt.ylabel("Frequência de Scrolling")
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/tela_vs_scrolling.png')
plt.show()

# Tempo de Tela vs Jogos Online
sns.scatterplot(x='Horas_Tempo_Tela',y='Horas_Jogos_Online',hue='Status_Estudante_Trabalho',data=df,size =1 )
plt.title("Tempo de Tela vs Horas de Jogo Online")
plt.xlabel("Horas de Tela")
plt.ylabel("Horas de Jogos")
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/tela_vs_jogos.png')
plt.show()

# Sono vs Tempo de Tela
sns.scatterplot(x='Horas_Sono_Diário',y='Horas_Tempo_Tela',data = df,size = 0.5)
plt.title("Horas de Sono Diário vs Tempo de Tela")
plt.xlabel("Horas de Sono")
plt.ylabel("Horas de Tela")
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/sono_vs_tela.png')
plt.show()

"""# Encoding"""

df.head()

le = LabelEncoder()
df['Gênero'] = pd.DataFrame(le.fit_transform(df['Gênero']))
df['Status_Estudante_Trabalho'] = pd.DataFrame(le.fit_transform(df['Status_Estudante_Trabalho']))
df['Risco_Burnout'] = pd.DataFrame(le.fit_transform(df['Risco_Burnout']))

df['Gênero'].value_counts()
df['Status_Estudante_Trabalho'].value_counts()

df.head()

ohe = OneHotEncoder(sparse_output = False)
df_country_transform = pd.DataFrame(ohe.fit_transform(df[['País']]),columns = ohe.get_feature_names_out(['País']))
df_content_transform = pd.DataFrame(ohe.fit_transform(df[['Preferência_Tipo_Conteúdo']]),columns = ohe.get_feature_names_out(['Preferência_Tipo_Conteúdo']))

df = pd.concat([df,df_country_transform,df_content_transform],axis =1)
df.drop(['País','Preferência_Tipo_Conteúdo'],axis = 1,inplace = True)

df.head()

"""# Splitting Input and Output"""

X = df.drop(['Risco_Burnout'],axis = 1)
y = le.fit_transform(df['Risco_Burnout'])

ss = StandardScaler()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

"""# Using DNN"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

num_classes = len(set(y))

model = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(32, activation='relu'),

    layers.Dense(num_classes, activation='softmax')

])

model.summary()

from tensorflow.keras.optimizers import Adam
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

"""# Early Stopping"""

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=100,
    callbacks=[early_stop],
    batch_size=512
)

"""# Visualization of DNN Accuracy and Loss"""

plt.figure(figsize=(10,5))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Acurácia do Modelo")
plt.ylabel("Acurácia")
plt.xlabel("Época")
plt.legend(['Treino', 'Validação'])
plt.grid(True)
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/acuracia_modelo.png')
plt.show()

plt.figure(figsize=(10,5))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Perda do Modelo (Loss)")
plt.ylabel("Perda")
plt.xlabel("Época")
plt.legend(['Treino', 'Validação'])
plt.grid(True)
plt.savefig('imagens_gen_z_mental_wellness_using_dnn/perda_modelo.png')
plt.show()

from sklearn.metrics import classification_report, accuracy_score,f1_score,confusion_matrix

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_acc)

y_pred = np.argmax(model.predict(X_test), axis=1)

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

pd.DataFrame(confusion_matrix(y_test, y_pred))